# Generated by Django 3.1.6 on 2021-02-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_smartphone_sd'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наявність SD карти'),
        ),
    ]
