# Generated by Django 3.1.6 on 2021-03-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210303_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=100, verbose_name='Ключ характеристики')),
                ('feature_name', models.CharField(max_length=255, verbose_name='Найменування характеристики')),
                ('postfix_for_value', models.CharField(blank=True, help_text='Наприклад для характеристики "Години роботи" до значення можна добавити постфікс "годин", і як результат - значення "10 годин"', max_length=20, null=True, verbose_name='Постфікс для значення')),
                ('use_in_filter', models.BooleanField(default=False, verbose_name='Використовувати фільтрації товарів в шаблоні')),
                ('filter_type', models.CharField(choices=[('radio', 'Радіокнопка'), ('checkbox', 'Чекбокс')], default='checkbox', max_length=20, verbose_name='Тип фільтра')),
                ('filter_measure', models.CharField(help_text='Одиниця вимірювання для конкретного фільтра. Наприклад "Частота процессора (Ghz). Одиницею вимірювання буде інформація в дужках"', max_length=50, verbose_name='Одиниця вимірювання для фільтра')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категорія')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatureValidators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Значення характеристики')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категорія')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.productfeatures', verbose_name='Характеристика')),
            ],
        ),
    ]
